# Generated by Django 4.2.6 on 2023-10-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=99, verbose_name="Слова")),
            ],
            options={
                "verbose_name": "Слово",
                "verbose_name_plural": "Слова",
            },
        ),
    ]
