# Generated by Django 4.2.6 on 2023-11-13 06:20

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gorynych_app", "0002_alter_word_word"),
    ]

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record", models.IntegerField(verbose_name="Рекорд")),
            ],
            options={
                "verbose_name": "Рекорд",
                "verbose_name_plural": "Рекорды",
            },
            managers=[
                ("object", django.db.models.manager.Manager()),
            ],
        ),
    ]
