# Generated by Django 4.2.6 on 2023-11-16 11:02

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gorynych_app", "0004_usergame"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="usergame",
            managers=[
                ("object", django.db.models.manager.Manager()),
            ],
        ),
    ]
