# Generated by Django 4.2.6 on 2023-11-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gorynych_app", "0008_alter_usergame_options_alter_record_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergame",
            name="record",
            field=models.IntegerField(default=0),
        ),
    ]
