# Generated by Django 4.2.6 on 2023-11-23 05:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gorynych_app", "0009_usergame_record"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Record",
        ),
    ]
