# Generated by Django 4.2.6 on 2023-12-03 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gorynych_app", "0012_usergame_game_for_record_alter_usergame_game"),
    ]

    operations = [
        migrations.CreateModel(
            name="Statictics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("victory", models.IntegerField(default=0, verbose_name="Победы")),
                ("dead_heat", models.IntegerField(default=0, verbose_name="Ничьи")),
                ("defeat", models.IntegerField(default=0, verbose_name="Поражения")),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
