# Generated by Django 4.2.6 on 2023-12-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gorynych_app", "0014_alter_statictics_options_statictics_number_of_games"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statictics",
            name="number_of_games",
            field=models.IntegerField(default=1, verbose_name="Количество игр"),
        ),
    ]
